#!/usr/bin/env python3
"""Generate the paper's LaTeX tables from experiment results.

    python scripts/export_paper_tables.py                 # after running experiments
    python scripts/export_paper_tables.py --placeholders   # before any results exist

Writes paper/generated/*.tex, which main.tex pulls in with \\input. Nothing in
that directory should be edited by hand: rerun this script instead, so the paper
can never drift from the results it reports.

With --placeholders it emits well-formed tables full of dashes, so the document
compiles and the layout can be checked before a single experiment has finished.
"""

import argparse
import glob
import json
import os
import statistics
import sys
from typing import Dict, List, Optional

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

HEADER = ("% Generated by scripts/export_paper_tables.py -- do not edit by hand.\n"
          "% Rerun that script to refresh these numbers.\n")

# Display name -> the variant directory it comes from. Keep in step with configs/.
VARIANTS = {
    "FaithLM (paper metric)":  "local_xcopa_vi_qwen_deepseek_paper_logprob",
    "FaithLM (symmetric)":     "local_xcopa_vi_qwen_deepseek_symmetric_logprob",
    "Negation baseline":       "local_xcopa_vi_qwen_baseline_negation_paper_logprob",
    "Identity baseline":       "local_xcopa_vi_qwen_baseline_identity_paper_logprob",
    "Shuffle baseline":        "local_xcopa_vi_qwen_baseline_shuffle_paper_logprob",
    "COPA-en (control)":       "local_copa_en_qwen_deepseek_paper_logprob",
}

DASH = "--"


def latex_escape(text: str) -> str:
    """Escape the characters that break a LaTeX build, leaving accents alone."""
    for old, new in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                     ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                     ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]:
        text = text.replace(old, new)
    return text


def load_variant(results_dir: str, variant: str) -> List[Dict]:
    records = []
    for path in sorted(glob.glob(os.path.join(results_dir, variant, "local", "sample-*.json"))):
        try:
            with open(path, encoding="utf-8") as f:
                record = json.load(f)
        except (json.JSONDecodeError, OSError):
            continue
        if not record.get("error"):
            records.append(record)
    return records


def stats_for(records: List[Dict]) -> Optional[Dict]:
    if not records:
        return None
    scores = [r.get("best_score", 0.0) for r in records]
    first = [r["iterations"][0]["score"] for r in records if r.get("iterations")]
    last = [r["iterations"][-1]["score"] for r in records if r.get("iterations")]
    return {
        "n": len(records),
        "accuracy": sum(bool(r.get("correct")) for r in records) / len(records),
        "faith": statistics.mean(scores),
        "stdev": statistics.stdev(scores) if len(scores) > 1 else 0.0,
        "zero": sum(1 for s in scores if s == 0.0) / len(scores),
        "first_iter": statistics.mean(first) if first else 0.0,
        "last_iter": statistics.mean(last) if last else 0.0,
    }


def fmt(value: Optional[float], places: int = 3) -> str:
    return DASH if value is None else f"{value:.{places}f}"


def write(path: str, body: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER + body)
    print(f"  {path}")


# ------------------------------------------------------------------ tables


def table_main_results(out_dir: str, data: Dict[str, Optional[Dict]]) -> None:
    rows = []
    for name in ("FaithLM (paper metric)", "FaithLM (symmetric)", "COPA-en (control)"):
        s = data.get(name)
        zero = f"{s['zero'] * 100:.1f}\\%" if s else DASH
        rows.append(
            f"{name} & {s['n'] if s else DASH} & {fmt(s['accuracy'] if s else None)} & "
            f"{fmt(s['faith'] if s else None)} & {fmt(s['stdev'] if s else None)} & "
            f"{zero} \\\\"
        )
    body = r"""
\begin{table}[t]
\centering
\small
\begin{tabular}{lrrrrr}
\toprule
\textbf{Setting} & \textbf{N} & \textbf{Acc.} & \textbf{Faith.} & \textbf{SD} & \textbf{Zero} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\caption{Task accuracy and faithfulness on Vietnamese XCOPA. \textbf{Faith.} is
the mean best faithfulness score per question; \textbf{Zero} is the fraction of
questions scoring exactly zero. TODO: replace this caption once the numbers are in.}
\label{tab:main}
\end{table}
"""
    write(os.path.join(out_dir, "main_results.tex"), body)


def table_baselines(out_dir: str, data: Dict[str, Optional[Dict]]) -> None:
    rows = []
    for name in ("FaithLM (paper metric)", "Negation baseline",
                 "Identity baseline", "Shuffle baseline"):
        s = data.get(name)
        rows.append(f"{name} & {fmt(s['faith'] if s else None)} & "
                    f"{fmt(s['stdev'] if s else None)} & {s['n'] if s else DASH} \\\\")
    body = r"""
\begin{table}[t]
\centering
\small
\begin{tabular}{lrrr}
\toprule
\textbf{Counterfactual source} & \textbf{Faith.} & \textbf{SD} & \textbf{N} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\caption{Replacing the LLM counterfactual generator with rule-based baselines.
The identity baseline returns the explanation unchanged, so its score is the
floor the metric assigns to a non-reversal. TODO: update caption.}
\label{tab:baselines}
\end{table}
"""
    write(os.path.join(out_dir, "baseline_comparison.tex"), body)


def table_error_analysis(out_dir: str, results_dir: str) -> None:
    records = load_variant(results_dir, VARIANTS["FaithLM (paper metric)"])
    if records:
        threshold = 0.1
        buckets = {
            "Correct, faithful":   sum(1 for r in records if r["correct"] and r["best_score"] > threshold),
            "Correct, unfaithful": sum(1 for r in records if r["correct"] and r["best_score"] <= threshold),
            "Wrong, faithful":     sum(1 for r in records if not r["correct"] and r["best_score"] > threshold),
            "Wrong, unfaithful":   sum(1 for r in records if not r["correct"] and r["best_score"] <= threshold),
        }
        total = len(records)
        rows = [f"{k} & {v} & {v / total * 100:.1f}\\% \\\\" for k, v in buckets.items()]
    else:
        rows = [f"{k} & {DASH} & {DASH} \\\\" for k in
                ("Correct, faithful", "Correct, unfaithful",
                 "Wrong, faithful", "Wrong, unfaithful")]

    body = r"""
\begin{table}[t]
\centering
\small
\begin{tabular}{lrr}
\toprule
\textbf{Category} & \textbf{Count} & \textbf{Share} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\caption{Predictions cross-tabulated against explanation faithfulness
(threshold $0.1$). ``Correct, unfaithful'' is the case of interest: the answer is
right, but the explanation does not track the decision. TODO: update caption.}
\label{tab:errors}
\end{table}
"""
    write(os.path.join(out_dir, "error_analysis.tex"), body)


def table_per_variant(out_dir: str, data: Dict[str, Optional[Dict]]) -> None:
    rows = []
    for name in VARIANTS:
        s = data.get(name)
        rows.append(
            f"{name} & {s['n'] if s else DASH} & {fmt(s['faith'] if s else None)} & "
            f"{fmt(s['first_iter'] if s else None)} & {fmt(s['last_iter'] if s else None)} \\\\"
        )
    body = r"""
\begin{table}[t]
\centering
\small
\begin{tabular}{lrrrr}
\toprule
\textbf{Variant} & \textbf{N} & \textbf{Best} & \textbf{Iter.\ 1} & \textbf{Iter.\ last} \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\caption{All variants, including the change from the first to the last
optimisation iteration. TODO: update caption.}
\label{tab:per-variant}
\end{table}
"""
    write(os.path.join(out_dir, "per_variant.tex"), body)


def table_dataset_stats(out_dir: str, results_dir: str) -> None:
    records = load_variant(results_dir, VARIANTS["FaithLM (paper metric)"])
    n_eval = str(len(records)) if records else DASH
    body = r"""
\begin{table}[t]
\centering
\small
\begin{tabular}{lrr}
\toprule
\textbf{Dataset} & \textbf{Split} & \textbf{Size} \\
\midrule
XCOPA-vi & test & 500 \\
XCOPA-vi (evaluated) & test & """ + n_eval + r""" \\
COPA-en (control) & train & 1{,}000 \\
\bottomrule
\end{tabular}
\caption{Datasets. The evaluated subset is drawn from the full split with a
fixed seed, so every run covers the same questions. TODO: update caption.}
\label{tab:data}
\end{table}
"""
    write(os.path.join(out_dir, "dataset_stats.tex"), body)


def table_setup(out_dir: str, results_dir: str) -> None:
    """Read the config back out of a summary file, so the paper cannot misreport it."""
    predictor = explainer = scorer = n_iter = sampling = seed = DASH
    for path in glob.glob(os.path.join(results_dir, "*", "summary_local.json")):
        try:
            with open(path, encoding="utf-8") as f:
                cfg = json.load(f).get("config", {})
        except (json.JSONDecodeError, OSError):
            continue
        # model_id may be null, meaning "the backend's default"; fall back to the
        # backend name so the table never reports a dash for a real run.
        pred_cfg = cfg.get("predictor", {})
        exp_cfg = cfg.get("explainer", {})
        predictor = latex_escape(pred_cfg.get("model_id") or pred_cfg.get("name") or DASH)
        explainer = latex_escape(exp_cfg.get("model_id") or exp_cfg.get("name") or DASH)
        scorer = latex_escape(cfg.get("metric", {}).get("scorer", DASH))
        run = cfg.get("run", {})
        n_iter = str(run.get("xai_iter", DASH))
        sampling = latex_escape(str(run.get("sampling", DASH)))
        seed = str(run.get("seed", DASH))
        break

    body = r"""
\begin{table}[t]
\centering
\small
\begin{tabular}{ll}
\toprule
\textbf{Component} & \textbf{Setting} \\
\midrule
Predictor & \texttt{""" + predictor + r"""} \\
Explainer & \texttt{""" + explainer + r"""} \\
Scorer & """ + scorer + r""" \\
Optimisation iterations & """ + n_iter + r""" \\
Question sampling & """ + sampling + r""" (seed """ + seed + r""") \\
\bottomrule
\end{tabular}
\caption{Experimental configuration, read back from the stored run config.
TODO: update caption.}
\label{tab:setup}
\end{table}
"""
    write(os.path.join(out_dir, "setup.tex"), body)


def main() -> None:
    parser = argparse.ArgumentParser(description="Export LaTeX tables for the paper")
    parser.add_argument("--results_dir", default="./results")
    parser.add_argument("--out_dir", default="./paper/generated")
    parser.add_argument("--placeholders", action="store_true",
                        help="Emit dash-filled tables without reading results")
    args = parser.parse_args()

    data: Dict[str, Optional[Dict]] = {}
    if not args.placeholders:
        for name, variant in VARIANTS.items():
            data[name] = stats_for(load_variant(args.results_dir, variant))
        found = sum(1 for v in data.values() if v)
        print(f"Found results for {found}/{len(VARIANTS)} variants")
        if not found:
            print("No results yet -- writing placeholders so the paper still compiles.")
    else:
        data = {name: None for name in VARIANTS}

    print("Writing:")
    results_dir = args.results_dir if not args.placeholders else "__none__"
    table_main_results(args.out_dir, data)
    table_baselines(args.out_dir, data)
    table_error_analysis(args.out_dir, results_dir)
    table_per_variant(args.out_dir, data)
    table_dataset_stats(args.out_dir, results_dir)
    table_setup(args.out_dir, results_dir)
    print("\nRerun after each experiment finishes to refresh the paper.")


if __name__ == "__main__":
    main()
